ci: currently mypy is simply not supported on pypy
Either we can't build ast-serialize because it's rusty, or mypy says:

  ERROR: Running mypy on PyPy is not supported yet.